### ISSUE TITLE
Ground Truth Detector - rejecting observations at same location

### ISSUE THREAD

**Issue by RajeshDM** [zkytony/cos-pomdp#17]
When the detector gets an observation from the ground truth information of AI2Thor, this line checks if the detection has happened at the exact same location and says don't count it as a detection because it happened more than once at the avg_loc

https://github.com/zkytony/cos-pomdp/blob/8b5bf36d028a0191d7c96ed757f62f4e2a77716d/cospomdp_apps/thor/detector.py#L152

What is the reason for this? would AI2Thor ground truth ideally not return the same location everytime for the object, so why would rejecting it be useful?
(It seems to be occurring in some scenes but not others, not sure why)

**Comment by zkytony** [comment]
`max_repeated_detections` is a tunable parameter. The intent here is to avoid re-considering evidence (i.e. detection of correlated objects) after they have been used. Intuitively, suppose you're looking for a remote control and believe it's nearby a pillow, but there are multiple pillows in the scene. If you detected a pillow, but didn't find the remote control nearby, you'd like to "forget" about that pillow. Of course due to randomness in search, we don't discard an evidence the first time we use it but discard it after using it `max_repeated_detections ` number of times.

**Comment by RajeshDM** [comment]
Got it. It makes sense that it is being done only for correlated objects and not the target objects. Thank you.
