### ISSUE TITLE
Robothor Scene

### ISSUE THREAD

**Issue by jeongeun980906** [zkytony/cos-pomdp#5]
Hello! Thank you for wonderful work.

I have been trying to run this code in robothor scene,  (e.g., FloorPlan-Val1-1) but the code tend to update the grid that is beyond the wall. Have you ever run this on robothor scene? If so, what should i change except for the scene name?

![Screenshot from 2022-07-16 17-16-43](https://user-images.githubusercontent.com/57895587/179346792-296e5867-5ab8-462a-b081-0c7a4a6a7ee5.png)
)

**Comment by zkytony** [comment]
Thanks for the question! I am glad you are trying this with RoboThor. I didn't consider running RoboThor scenes with this system - the walls were definitely one concern. But I think with some adjustment with the sensor model, the system (especially the object search planning algorithm) can still be applied.

Specifically, you need to develop a sensor model that can take into account occlusion by the walls. To help with this, [thortils](https://github.com/zkytony/thortils/blob/v3.3.4/thortils/grid_map.py) has a function called [`blocked`](https://github.com/zkytony/thortils/blob/v3.3.4/thortils/grid_map.py#L245) that returns whether two locations on the map are blocked by an obstacle. You can look at [sensors.py](https://github.com/zkytony/cos-pomdp/blob/master/cospomdp/models/sensors.py#L75) for implementation of the fan-shape sensor. You may want to modify the `in_range` function to consider obstacles.

In an early phase of this project, I implemented a grid map with walls and a sensor model that take that into account, where the agent doesn't begin with the environment map and needs to explore the environment while searching for the target object. In this example, the agent tries to search for a SaltShaker by first searching for the Kitchen and use spatial correlation to reduce uncertainty about the SaltShaker's location.

![img](https://camo.githubusercontent.com/b49e053ef3f7058d823ec4dbb3e71e5d20958a46693fc94a7a70f0c6e97bce5f/68747470733a2f2f692e696d6775722e636f6d2f494575684a516a2e676966)

The grid map representation here is a little different (the walls are edges, instead of obstacles). I am pasting the `within_range` function used in the sensor model there (same purpose as "in_range"). This may help. (This is definitely not the only, or the most efficient way to consider occlusion by fan-shaped sensor models, so you may totally come up with your own way!)

```python
    def within_range(self, robot_pose, point,
                     grid_map=None, cache=None,
                     walls_to_consider=None,
                     return_intersecting_wall=False):
        """Returns true if the point is within range of the sensor (i.e. visible).
        To do this need to check if any wall is closer to the robot along the
        direction of the beam from robot to the `point`.x
        Args:
            robot_pose (tuple): (x,y,theta) pose of the robot
            point (tuple): (x,y) point to determine if in range
            grid_map (GridMap): The grid map whose walls can cause occlusions
            cache (SensorCache): The cache that helps computing this faster
            return_intersecting_wall (bool): True if want to return the wall that
                is intersecting the sensor beam. NOTE: This parameter affects what
                the cache stores. If True, then the cache will also store the intersecting
                wall for this (robot_pose, point) pair."""
        if cache is not None and grid_map is not None:
            if not cache.serving(grid_map):
                raise ValueError("Cache is already used to serve for map %s" % cache.map_serving)

        if cache is not None:
            assert cache.sensor_name == self.name
            result = cache.get(robot_pose, point)
            if result is not None:
                detectable, intersecting_wall = result
                if return_intersecting_wall:
                    return detectable, intersecting_wall
                else:
                    return detectable

        detectable = True
        intersecting_wall = None

        if robot_pose[:2] != point:
            point_dist, point_bearing = self.shoot_beam(robot_pose, point)
            point_in_range = (in_range(point_dist, (self.min_range, self.max_range)))\
                and (in_range(point_bearing, self._fov_left)\
                     or in_range(point_bearing, self._fov_right))
            if not point_in_range:
                detectable = False
            else:
                if walls_to_consider is None:
                    if grid_map is not None:
                        walls_to_consider = grid_map.walls
                    else:
                        print("Warning: within_range is not using wall intersection")
                        walls_to_consider = set()

                # Check walls
                for objid in walls_to_consider:
                    wall = walls_to_consider[objid]
                    if wall.intersect(robot_pose[:2], point):
                        detectable = False
                        intersecting_wall = (objid, wall)
                        break

        if cache is not None:
            assert cache.sensor_name == self.name
            cache.put(robot_pose, point, detectable, intersecting_wall)

        if return_intersecting_wall:
            return detectable, intersecting_wall
        else:
            return detectable
```
In this case, the intersection is handled by "wall.intersect", which just checks if the line segment intersects with the edge that represents the wall. I think you can achieve something of similar effect with the `blocked` function in the current grid_map (IMO better because it's an occupancy grid map that is more versatile).

I am happy to share the code for this early phase if necessary. Please reach out to me by email. Thanks!

**Comment by jeongeun980906** [comment]
Thank you so much for your help!

Unfortunately, I found the 'blocked' function returns both on the objects
and the wall, which is not appropriate for updating beliefs.

I couldn't find any function which only returns the wall on Ai2Thor so
far.. But if you have any other suggestions, please let me know

Best Regards

Jeonguen

2022년 7월 17일 (일) 오전 1:01, Kaiyu Zheng ***@***.***>님이 작성:

**Comment by zkytony** [comment]
I see. If you can distinguish the grids for the wall from the grids that are potential object locations (taken as input by the cos-pomdp planner), then you can only consider blocking to happen on the wall grids. I think walls in Ai2THOR are objects with bounding boxes. You may be able to project those boxes onto the grid map, and assign those grids to have a label "wall".

**Comment by zkytony** [comment]
I wonder if it is possible to remove all objects from a scene, and then run the mapping algorithm in thortils, which gives you obstacles that are just walls. This could be one way to label the walls as well. Essentially you'd like to have a layout map with just walls.

**Comment by jeongeun980906** [comment]
Thanks!

I will try as you recommended, And get back to you

Thank you so much for your help!

Best Regards

Jeongeun

**Comment by RajeshDM** [comment]
Is the code for checking if the view is occluded by walls available somewhere? I am trying to do the same as well.

**Comment by RajeshDM** [comment]
Thank you for the reference. @jeongeun980906 Do you have any running code for AI2Thor that can solve this problem of sensors through walls? It would greatly help my project. Thank you
